NAVIGATION
font: Open Sans
size: 16px
background: linear-gradient(90deg, #d1d1d1 0%, #ffffff 1%, #ffffff 65%, #d1d1d1 100%)

ICONS
print, fullscreen, menu, attachments, audio, completion, navigation

HEADER
background: #AD1620
text: white
shadow: none
title: on
description: off
progress: on

FOOTER
background: none
text: black
copyright: on

ITEM
background: transparent
text: black
padding: 1rem
shadow: none

SELECTION
background: #C3686A
text: white
shadow: rgba(0,0,0,.25)
